name: Full Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build_all:
        description: 'Build all projects'
        required: true
        default: true
        type: boolean
      build_jans_agama:
        description: 'Build jans-agama'
        required: false
        default: false
        type: boolean
      build_jans_auth_server:
        description: 'Build jans-auth-server'
        required: false
        default: false
        type: boolean
      build_jans_bom:
        description: 'Build jans-bom'
        required: false
        default: false
        type: boolean
      build_jans_casa:
        description: 'Build jans-casa'
        required: false
        default: false
        type: boolean
      build_jans_config_api:
        description: 'Build jans-config-api'
        required: false
        default: false
        type: boolean
      build_jans_core:
        description: 'Build jans-core'
        required: false
        default: false
        type: boolean
      build_jans_fido2:
        description: 'Build jans-fido2'
        required: false
        default: false
        type: boolean
      build_jans_keycloak_link:
        description: 'Build jans-keycloak-link'
        required: false
        default: false
        type: boolean
      build_jans_keycloak: 
        description: 'Build jans-keycloak'
        required: false
        default: false
        type: boolean
      build_jans_keycloak_integration:
        description: 'Build jans-keycloak-integration'
        required: false
        default: false
        type: boolean
      build_jans_link: 
        description: 'Build jans-link'
        required: false
        default: false
        type: boolean
      build_jans_lock:
        description: 'Build jans-lock'
        required: false
        default: false
        type: boolean
      build_jans_orm:
        description: 'Build jans-orm'
        required: false
        default: false
        type: boolean
      build_jans_scim:
        description: 'Build jans-scim'
        required: false
        default: false
        type: boolean
jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      VERSION_NAME: main
      MAVEN_SKIP_TESTS: true
      PROFILE_NAME: ""
      CONTAINER_NAME: ""
      DEVELOPMENT_BUILD: ""
      CVSS_SCORE: ""
      SKIP_FINDBUGS: ""

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Delete workspace before build
      run: rm -rf ${{ github.workspace }}/*

    - name: Set up Maven
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: 'maven'

    - name: Prepare directories and profiles for build
      run: |
        if [[ "${{ github.event.inputs.build_all }}" == "true" || "${{ github.event.inputs.build_jans_agama }}" == "true" ]]; then
          # jans-agama specific setup
          echo "Setting up jans-agama"
        fi
        if [[ "${{ github.event.inputs.build_all }}" == "true" || "${{ github.event.inputs.build_jans_auth_server }}" == "true" ]]; then
          # jans-auth-server specific setup
          echo "Setting up jans-auth-server"

        fi

    - name: Build with Maven
      run: |
        if [[ "${{ github.event.inputs.build_all }}" == "true" || "${{ github.event.inputs.build_jans_agama }}" == "true" ]]; then
          mvn -f jans-agama/pom.xml -Dcfg=${{ env.PROFILE_NAME }} -Dmaven.test.skip=${{ env.MAVEN_SKIP_TESTS }} clean compile install
        fi
        if [[ "${{ github.event.inputs.build_all }}" == "true" || "${{ github.event.inputs.build_jans_auth_server }}" == "true" ]]; then
          mvn -f jans-agama/pom.xml -Dcfg=${{ env.PROFILE_NAME }} -Dmaven.test.skip=${{ env.MAVEN_SKIP_TESTS }} -Ddevelopment-build=${{ env.DEVELOPMENT_BUILD }} -Dcvss-score=${{ env.CVSS_SCORE }} -Dfindbugs.skip=${{ env.SKIP_FINDBUGS }} -Ddependency.check=${{ env.DEPENDENCY_CHECK }} -U -fae clean compile install javadoc:javadoc site
        fi
    