name: Jans Auth Server CI/CD

on:
  push:
    branches:
      - migration/jenkins-pipelines
  schedule:
    - cron: '0 8 * * *'
  pull_request:
    branches:
      - migration/jenkins-pipelines
  workflow_dispatch:
    inputs:
      project:
        description: 'Select the project to build'
        required: true
        default: 'jans-auth-server'
        type: choice
        options:
          - jans-auth-server


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      VERSION_NAME: main
      MAVEN_SKIP_TESTS: true
      PROFILE_NAME: "default"
      CONTAINER_NAME: "ubuntu20-ldap"
      # DEVELOPMENT_BUILD: ""
      # CVSS_SCORE: ""
      # SKIP_FINDBUGS: "true"
      # DEPENDENCY_CHECK: ""

    strategy:
      matrix:
        service:
          - "jans-bom"
          - "jans-orm"
          - "jans-core"
          - "jans-lock"
          - "jans-agama"
          - "jans-auth-server"
          - "jans-link"
          - "jans-fido2"
          - "jans-scim"
          - "jans-keycloak-link"
          - "jans-config-api"
          - "jans-keycloak"
          - "jans-casa"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Set up Java 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Set up Maven
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: 'maven'

    - name: Build jans-auth-server
      run: |
        mvn -f jans-bom/pom.xml -Dcfg=${{ env.PROFILE_NAME }} -Dmaven.test.skip=${{ env.MAVEN_SKIP_TESTS }} clean compile install

    - name: Publish to GitHub Packages
      run: mvn -B deploy -Dcfg=${{ env.PROFILE_NAME }} -Dmaven.test.skip=${{ env.MAVEN_SKIP_TESTS }}
      working-directory: jans-bom
      env:
        GITHUB_TOKEN: ${{ secrets.JANS_TOKEN }}

    - name: Archive results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-results
        path: jans-auth-server/target

    - name: Send notification on failure
      if: failure()
      run: echo "Build failed"
