name: Jans Fido2

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      VERSION_NAME: main
      MAVEN_SKIP_TESTS: true
      PROFILE_NAME: ""
      DEVELOPMENT_BUILD: ""

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Delete workspace before build
      run: rm -rf ${{ github.workspace }}/*

    - name: Set up Maven
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -Dmaven.test.skip=${{ env.MAVEN_SKIP_TESTS }} -Dcfg=${{ env.PROFILE_NAME }} -Ddevelopment-build=${{ env.DEVELOPMENT_BUILD }} clean compile test-compile install spotbugs:spotbugs site

    - name: Execute build docker-image workflow
      env:
        GITGLUUTOKEN: ${{ secrets.GITGLUUTOKEN }}
      run: |
        curl --location --request POST 'https://api.github.com/repos/JanssenProject/jans-cloud-native/actions/workflows/15443035/dispatches' \
        --header 'Authorization: Bearer '${{ secrets.GITGLUUTOKEN }} \
        --header 'Content-Type: application/json' \
        --data '{"ref":"master", "inputs": { "services":"docker-jans-lock" }}'

    - name: Archive results
      uses: actions/upload-artifact@v3
      with:
        name: build-results
        path: target

    - name: Notify on failure
      if: failure()
      run: |
        curl -X POST -H 'Content-Type: application/json' -d '{"channel": "bot_reporter", "text": "Build ${{ github.run_id }} for job Build Jans Fido2 failed.\r"}' https://rocketchat-webhook-url
        
    - name: Notify on unstable
      if: always() && !success() && !failure()
      run: |
        curl -X POST -H 'Content-Type: application/json' -d '{"channel": "bot_reporter", "text": "Build ${{ github.run_id }} for job Build Jans Fido2 is unstable.\r"}' https://rocketchat-webhook-url
        
    - name: Notify on success
      if: success()
      run: |
        curl -X POST -H 'Content-Type: application/json' -d '{"channel": "bot_reporter", "text": "Build ${{ github.run_id }} for job Build Jans Fido2 finished successfully.\r"}' https://rocketchat-webhook-url


