name: Jans Scim

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      VERSION_NAME: main
      MAVEN_SKIP_TESTS: true
      PROFILE_NAME: ""
      CONTAINER_NAME: ""

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Delete workspace before build
      run: rm -rf ${{ github.workspace }}/*

    - name: Set up Maven
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: 'maven'

    - name: Delete old profiles
      run: |
        cd jans-scim

        rm -rf ./client/profiles/${{ env.PROFILE_NAME }}

        if [[ $MAVEN_SKIP_TESTS == "true" ]]; then
          echo "Configuring to use default profile in build without tests execution"

          cp -rf ./client/profiles/default ./client/profiles/${{ env.PROFILE_NAME }}
        else
          if [[ $TEST_CONF_IN_HOST == "true" ]]; then
            scp -r -P 22222 root@${{ env.PROFILE_NAME }}:/opt/jans/jans-setup/output/test/scim-client ./
          else
            scp -r -P 22222 root@${{ env.PROFILE_NAME }}:/var/snap/lxd/common/lxd/storage-pools/default/containers/$CONTAINER_NAME/rootfs/opt/jans/jans-setup/output/test/scim-client ./
          fi

          mkdir -p ./client/profiles/${{ env.PROFILE_NAME }}

          cp ./scim-client/client/config-scim-test.properties ./client/profiles/${{ env.PROFILE_NAME }}

          rm -rf ./scim-client
        fi

    - name: Build with Maven
      run: mvn -Dmaven.test.skip=${{ env.MAVEN_SKIP_TESTS }} -Dcfg=${{ env.PROFILE_NAME }} clean compile install spotbugs:spotbugs site

    - name: Move javadocs to appropriate location
      run: |
        cd jans-scim

        rm -rf ./scim-client
        rm -rf ./client/profiles/${{ env.PROFILE_NAME }}

        mkdir -p /var/www/html/javadocs/jans-scim/$VERSION_NAME

        rm -rf /var/www/html/javadocs/jans-scim/${{ env.VERSION_NAME}}/client/{apidocs,css,images} 
        rm -rf /var/www/html/javadocs/jans-scim/${{ env.VERSION_NAME}}/model/{apidocs,css,images} 
        rm -rf /var/www/html/javadocs/jans-scim/${{ env.VERSION_NAME}}/server/{apidocs,css,images} 

        mkdir -p /var/www/html/javadocs/jans-scim/$VERSION_NAME/{client,model,server}

        cp -rv ./client/target/site/apidocs/* /var/www/html/javadocs/jans-scim/${{ env.VERSION_NAME}}/client/
        cp -rv ./model/target/site/apidocs/* /var/www/html/javadocs/jans-scim/${{ env.VERSION_NAME}}/model/
        cp -rv ./server/target/site/apidocs/* /var/www/html/javadocs/jans-scim/${{ env.VERSION_NAME}}/server/

    - name: Execute build docker-image workflow
      env:
        GITGLUUTOKEN: ${{ secrets.GITGLUUTOKEN }}
      run: |
        curl --location --request POST 'https://api.github.com/repos/JanssenProject/jans-cloud-native/actions/workflows/15443035/dispatches' \
        --header 'Authorization: Bearer '${{ secrets.GITGLUUTOKEN }} \
        --header 'Content-Type: application/json' \
        --data '{"ref":"master", "inputs": { "services":"docker-jans-lock" }}'

    - name: Archive results
      uses: actions/upload-artifact@v3
      with:
        name: build-results
        path: target

    - name: Notify on failure
      if: failure()
      run: |
        curl -X POST -H 'Content-Type: application/json' -d '{"channel": "bot_reporter", "text": "Build ${{ github.run_id }} for job Build Jans SCIM failed.\r"}' https://rocketchat-webhook-url
        
    - name: Notify on unstable
      if: always() && !success() && !failure()
      run: |
        curl -X POST -H 'Content-Type: application/json' -d '{"channel": "bot_reporter", "text": "Build ${{ github.run_id }} for job Build Jans SCIM is unstable.\r"}' https://rocketchat-webhook-url
        
    - name: Notify on success
      if: success()
      run: |
        curl -X POST -H 'Content-Type: application/json' -d '{"channel": "bot_reporter", "text": "Build ${{ github.run_id }} for job Build Jans SCIM finished successfully.\r"}' https://rocketchat-webhook-url


